spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/resliv_task
    username: postgres
    password:

  jpa:
    hibernate:
      ddl-auto: create-drop
      show-sql: true
      database: postgresql
      database-platform: org.hibernate.dialect.PostgreSQLDialect
      open-in-view: false
      generate-ddl: true
    properties.hibernate.temp.use_jdbc_metadata_defaults: false
    properties.hibernate.dialect: org.hibernate.dialect.PostgreSQL94Dialect
